capiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo-worker
  labels:
    app: springboot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo-worker
  template:
    metadata:
      labels:
        app: springboot-demo-worker
    spec:
      containers:
      - name: worker
        image: springboot-demo-app:local    
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
