apiVersion: v1
kind: Service
metadata:
  name: springboot-demo-worker
  labels:
    app: springboot-demo
spec:
  selector:
    app: springboot-demo-worker
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP                         # or LoadBalancer/NodePort if needed
