apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-demo-app
  namespace: argocd
spec:
  project: default
  source:
    # Update this to your repo URL and preferred branch.
    repoURL: https://github.com/Arunim08/Test_Invariant.git
    targetRevision: main
    path: K8s
  destination:
    server: https://kubernetes.default.svc
    namespace: springboot-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

