apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-demo-ingress
  namespace: springboot-demo
  annotations:

    kubernetes.io/ingress.class: "nginx" 
   
spec:
  ingressClassName: nginx 
  rules:
  - host: springboot-demo.yourdomain.com  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: springboot-demo 
            port:
              number: 8080 
  tls:
  - hosts:
    - springboot-demo.yourdomain.com
    secretName: springboot-demo-tls  
